/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by vite-plugin-global-types
export {}

import * as IndexTypes from 'index'

declare global {
  type Foo<T = number> = IndexTypes.Foo<T>
  interface Bar extends IndexTypes.Bar {}
}
