import fs from 'fs';
import path from 'path';

export interface InputOption {
  path: string;
  filePattern?: RegExp;
  excludeDirs?: string[];
  importAs?: string;
  absPath?: string; // filled internally
}

export interface GenerateOptions {
  inputs: (string | InputOption)[];
  outputs: string[];
}

/**
 * Generate global.d.ts from multiple inputs
 */
export function generateGlobalTypes(options: GenerateOptions) {
  const { inputs, outputs } = options;

  let allTypes: {
    name: string;
    leftGenerics: string;
    rightGenerics: string;
    alias: string;
  }[] = [];
  let allInterfaces: { name: string; alias: string }[] = [];
  const imports: string[] = [];

  const resolvedOutputs = outputs.map((o) => path.resolve(o));
  const outputDir = path.dirname(resolvedOutputs[0]);

  const inputFiles: string[] = [];

  inputs.forEach((input) => {
    let absPath: string;
    let importAs: string | undefined;
    let pattern: RegExp = /.*/;
    let excludeDirs: string[] = [];

    if (typeof input === 'string') {
      absPath = path.resolve(input);
    } else {
      absPath = path.resolve(input.path);
      importAs = input.importAs;
      pattern = input.filePattern || pattern;
      excludeDirs = input.excludeDirs || [];
    }

    if (fs.existsSync(absPath) && fs.statSync(absPath).isDirectory()) {
      inputFiles.push(
        ...findFiles(absPath, { filePattern: pattern, excludeDirs })
      );
    } else {
      inputFiles.push(absPath);
    }

    if (typeof input !== 'string') {
      input.absPath = absPath;
      input.importAs = importAs;
    }
  });

  if (inputFiles.length === 0) throw new Error('No input files found');

  inputFiles.forEach((file) => {
    const content = fs.readFileSync(file, 'utf-8');
    const inputOption = (inputs as InputOption[]).find(
      (inp: any) => inp?.absPath && file.startsWith(inp.absPath)
    );
    const alias = generateAliasName(file, outputDir);
    const importPath =
      inputOption?.importAs ||
      path.relative(outputDir, file).replace(/\\/g, '/').replace(/\.ts$/, '');
    imports.push(`import * as ${alias} from '${importPath}'`);

    const typeRegex = /^\s*export\s+type\s+([A-Za-z0-9_]+)(<[^>]+>)?/gm;
    const interfaceRegex = /^\s*export\s+interface\s+([A-Za-z0-9_]+)/gm;

    let match;
    while ((match = typeRegex.exec(content)) !== null) {
      const generics = match[2] || '';
      allTypes.push({
        name: match[1],
        leftGenerics: generics,
        rightGenerics: generics.replace(/\s*=\s*[^,>]+/g, ''),
        alias,
      });
    }
    while ((match = interfaceRegex.exec(content)) !== null) {
      allInterfaces.push({ name: match[1], alias });
    }
  });

  const outputContent = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by vite-plugin-global-types
export {}

${imports.join('\n')}

declare global {
${allTypes
  .map(
    (t) =>
      `  type ${t.name}${t.leftGenerics} = ${t.alias}.${t.name}${t.rightGenerics}`
  )
  .join('\n')}
${allInterfaces
  .map((i) => `  interface ${i.name} extends ${i.alias}.${i.name} {}`)
  .join('\n')}
}
`;

  resolvedOutputs.forEach((outputPath) => {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, outputContent, 'utf-8');
  });
}

// -----------------------
// Helpers
// -----------------------

function findFiles(
  baseDir: string,
  {
    filePattern = /.*/,
    excludeDirs = [],
  }: { filePattern?: RegExp; excludeDirs?: string[] } = {}
): string[] {
  let results: string[] = [];
  const files = fs.readdirSync(baseDir, { withFileTypes: true });
  for (const file of files) {
    const fullPath = path.join(baseDir, file.name);
    if (file.isDirectory()) {
      if (excludeDirs.includes(file.name)) continue;
      results.push(...findFiles(fullPath, { filePattern, excludeDirs }));
    } else if (file.isFile() && filePattern.test(file.name)) {
      results.push(fullPath);
    }
  }
  return results;
}

function generateAliasName(filePath: string, outputDir: string): string {
  const relativePath = path.relative(outputDir, filePath).replace(/\\/g, '/');
  const noExt = relativePath.replace(/\.ts$/, '');
  const parts = noExt
    .split('/')
    .filter(
      (p) => p && p !== '.' && p !== '..' && p !== 'src' && p !== 'types'
    );
  const pascalCase = parts
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
  return pascalCase + 'Types';
}
