import fs from 'fs';
import path from 'path';

export interface InputOption {
  path: string;
  filePattern?: RegExp;
  excludeDirs?: string[];
  importAs?: string;
}

export interface GenerateOptions {
  inputs: (string | InputOption)[];
  outputs: string[];
}

interface ResolvedInput extends InputOption {
  absPath: string;
}

/**
 * Generate global.d.ts from multiple inputs
 */
export function generateGlobalTypes(options: GenerateOptions) {
  const { inputs, outputs } = options;

  let allTypes: {
    name: string;
    leftGenerics: string;
    rightGenerics: string;
    alias: string;
  }[] = [];
  let allInterfaces: {
    name: string;
    alias: string;
    leftGenerics: string;
    rightGenerics: string;
  }[] = [];
  const imports: string[] = [];

  const resolvedOutputs = outputs.map((o) => path.resolve(o));
  const outputDir = path.dirname(resolvedOutputs[0]);

  const inputFiles: string[] = [];

  const resolvedInputs: ResolvedInput[] = inputs.map((input) => {
    const isString = typeof input === 'string';
    const inputPath = isString ? input : input.path;
    const absPath = path.resolve(inputPath);
    return {
      path: inputPath,
      filePattern: !isString ? input.filePattern : undefined,
      excludeDirs: !isString ? input.excludeDirs : undefined,
      importAs: !isString ? input.importAs : undefined,
      absPath,
    };
  });

  resolvedInputs.forEach((input) => {
    if (fs.existsSync(input.absPath)) {
      if (fs.statSync(input.absPath).isDirectory()) {
        inputFiles.push(
          ...findFiles(input.absPath, {
            filePattern: input.filePattern || /.*/,
            excludeDirs: input.excludeDirs || [],
          })
        );
      } else {
        inputFiles.push(input.absPath);
      }
    }
  });

  if (inputFiles.length === 0) throw new Error('No input files found');

  inputFiles.forEach((file) => {
    const content = fs.readFileSync(file, 'utf-8');
    const inputOption = resolvedInputs.find((inp) =>
      file.startsWith(inp.absPath)
    );
    const alias = generateAliasName(file, outputDir);
    const importPath =
      inputOption?.importAs ||
      path.relative(outputDir, file).replace(/\\/g, '/').replace(/\.ts$/, '');
    imports.push(`import * as ${alias} from '${importPath}'`);

    const typeRegex = /^\s*export\s+type\s+([A-Za-z0-9_]+)(<.*>)?/gm;
    const interfaceRegex = /^\s*export\s+interface\s+([A-Za-z0-9_]+)(<.*>)?/gm;

    let match;
    while ((match = typeRegex.exec(content)) !== null) {
      const generics = match[2] || '';
      allTypes.push({
        name: match[1],
        leftGenerics: generics,
        rightGenerics: extractGenericNames(generics),
        alias,
      });
    }
    while ((match = interfaceRegex.exec(content)) !== null) {
      const generics = match[2] || '';
      allInterfaces.push({
        name: match[1],
        alias,
        leftGenerics: generics,
        rightGenerics: extractGenericNames(generics),
      });
    }
  });

  const outputContent = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by vite-plugin-global-types
export {}

${imports.join('\n')}

declare global {
${allTypes
  .map(
    (t) =>
      `  type ${t.name}${t.leftGenerics} = ${t.alias}.${t.name}${t.rightGenerics}`
  )
  .join('\n')}
${allInterfaces
  .map(
    (i) =>
      `  interface ${i.name}${i.leftGenerics} extends ${i.alias}.${i.name}${i.rightGenerics} {}`
  )
  .join('\n')}
}
`;

  resolvedOutputs.forEach((outputPath) => {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, outputContent, 'utf-8');
  });
}

// -----------------------
// Helpers
// -----------------------

export function extractGenericNames(generics: string): string {
  if (!generics.startsWith('<') || !generics.endsWith('>')) {
    return generics;
  }
  const content = generics.substring(1, generics.length - 1);
  let depth = 0;
  let lastSplit = 0;
  const parts: string[] = [];
  for (let i = 0; i < content.length; i++) {
    if (content[i] === '<') {
      depth++;
    } else if (content[i] === '>') {
      depth--;
    } else if (content[i] === ',' && depth === 0) {
      parts.push(content.substring(lastSplit, i));
      lastSplit = i + 1;
    }
  }
  parts.push(content.substring(lastSplit));

  return `<${parts
    .map((part) => part.split('=')[0].split(' extends ')[0].trim())
    .join(', ')}>`;
}

export function findFiles(
  baseDir: string,
  {
    filePattern = /.*/,
    excludeDirs = [],
  }: { filePattern?: RegExp; excludeDirs?: string[] } = {}
): string[] {
  let results: string[] = [];
  const files = fs.readdirSync(baseDir, { withFileTypes: true });
  for (const file of files) {
    const fullPath = path.join(baseDir, file.name);
    if (file.isDirectory()) {
      if (excludeDirs.includes(file.name)) continue;
      results.push(...findFiles(fullPath, { filePattern, excludeDirs }));
    } else if (file.isFile() && filePattern.test(file.name)) {
      results.push(fullPath);
    }
  }
  return results;
}

export function generateAliasName(filePath: string, outputDir: string): string {
  const relativePath = path.relative(outputDir, filePath).replace(/\\/g, '/');
  const noExt = relativePath.replace(/\.ts$/, '');
  const parts = noExt
    .split('/')
    .filter(
      (p) => p && p !== '.' && p !== '..' && p !== 'index' && p !== 'types'
    );

  if (parts.length === 0) {
    parts.push(path.basename(noExt));
  }

  const pascalCase = parts
    .map((p) =>
      p
        .split(/[^A-Za-z0-9]/) // Split by non-alphanumeric (e.g. '-')
        .filter(Boolean)
        .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
        .join('')
    )
    .join('');
  return pascalCase + 'Types';
}
